name: Library CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Create directories
      run: |
        mkdir -p src/models src/controllers src/views src/utils
        mkdir -p tests data
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest==7.4.3 flake8==7.0.0
    
    - name: Check code structure
      run: |
        if [ ! -f "src/models/db.py" ]; then
          echo "Error: src/models/db.py not found"
          exit 1
        fi
        if [ ! -f "tests/test_db.py" ]; then
          echo "Error: tests/test_db.py not found"
          exit 1
        fi
    
    - name: Lint with flake8
      run: |
        flake8 src tests --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 src tests --max-line-length=127 --statistics
    
    - name: Run tests
      run: |
        PYTHONPATH=$PWD pytest tests/ -v
